const ClubHeads = [
  {
    name: "Dr. RR Panda",
    position: "Clubs Chairmen",
    email: "clubchairman@abes.ac.in",
    dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
  },
  {
    name: "Dr. Puneet Kumar Aggarwal",
    position: "Club Counselor",
    email: "puneet.aggarwal@abes.ac.in",
    dp: "https://i.ibb.co/F3GJb69/punit-kragrawal.png",
  },
  {
    name: "Mr. Devendra K. Misra",
    position: "Club Member - CSE",
    email: "devendra.misra@abes.ac.in",
    dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
  },
  {
    name: "Ms. Bharti Shukla",
    position: "Club Member - CSE",
    email: "bharati.shukla@abes.ac.in",
    dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
  },
  {
    name: "Mr Abhishek Kumar Gupta",
    position: "Club Member - EN",
    email: "abhishek.gupta@abes.ac.in",
    dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
  },
  {
    name: "Dr. Abhishek Pandey",
    position: "Club Member - ME",
    email: "abhishek.pandey@abes.ac.in",
    dp: "https://i.ibb.co/ccY60dB/abhisek-pandey.jpg",
  },
  {
    name: "Mr. Uzair Khan",
    position: "Club Member - Civil",
    email: "uzair.khan@abes.ac.in",
    dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
  },
  {
    name: "Dr. Ganesh  Kumar Thakur",
    position: "Club Member - ASH",
    email: "ganesh.thakur@abes.ac.in",
    dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
  },
  {
    name: "Ms. Tania Gupta",
    position: "Club Member - EC",
    email: "tania.gupta@abes.ac.in",
    dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
  },
  {
    name: "Mr. Ravindra Chauhan",
    position: "Club Member - CS",
    email: "ravindra.chauhan@abes.ac.in",
    dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
  },
  {
    name: "Mr. Dhyanendra Jain",
    position: "Club Member - CSE-AIML",
    email: "dhyanendra.jain@abes.ac.in",
    dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
  },
  {
    name: "Mr. Amit Kumar Pandey",
    position: "Club Member - CSE-DS",
    email: "amitpandey@abes.ac.in",
    dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
  },
];

const Core = [
  {
    id: "1",
    name: "Raghav Shah",
    position: "General Secretary",
    dp: "https://i.ibb.co/cbP942f/raghav-shah.jpg",
    insta: "https://www.instagram.com/_raghav._.daada/",
    email: "raghav.20b0311207@abes.ac.in",
  },
  {
    id: "2",
    name: "Mukul Sharma",
    position: "Joint Secretary",
    dp: "https://i.ibb.co/rdcFgSH/mukul-sharma.jpg",
    insta: "https://www.instagram.com/mukul_21947/",
    email: "mukul.20b0311058@abes.ac.in",
  },
  {
    id: "3",
    name: "Pankaj Kumar",
    position: "Digital Head",
    dp: "https://i.ibb.co/hgvZgHH/pankaj-kumar.png",
    insta: "https://www.instagram.com/pankajkr987",
    email: "pankaj.20b0101181@abes.ac.in",
  },
  {
    id: "4",
    name: "Prashant",
    position: "Social Media Co-ordinator",
    dp: "https://i.ibb.co/DW9HTzz/prashant-roy.jpg",
    insta: "https://www.instagram.com/Herobrahman",
    email: "prashant.20b0311133@abes.ac.in",
  },
  {
    id: "5",
    name: "Maitri Katiyar",
    position: "Social Media Co-ordinator",
    dp: "https://i.ibb.co/JFQWyP5/maitri-katiyar.jpg",
    insta: "https://www.instagram.com/maitri__katiyar",
    email: "maitri.20b0101136@abes.ac.in",
  },
  {
    id: "6",
    name: "Subbu Suman",
    position: "Design Head",
    dp: "https://i.ibb.co/Sfzz8GZ/subbu-suman.jpg",
    insta: "https://www.instagram.com/i_subbu.rajput",
    email: "subbu.20b0401048@abes.ac.in",
  },
  {
    id: "7",
    name: "Lakshya Sharma",
    position: "Senior Co-ordinator",
    dp: "https://i.ibb.co/CWTWVQW/lakshya-sharma.png",
    insta: "https://www.instagram.com/panditlakshya22",
    email: "lakshya.20b0101021@abes.ac.in",
  },
  {
    id: "8",
    name: "Pratham Maurya",
    position: "Promotion Head",
    dp: "https://i.ibb.co/nsGLy8f/pratham-maurya.jpg",
    insta: "https://www.instagram.com/prat.ham3072",
    email: "pratham.20b0311181@abes.ac.in",
  },
  {
    id: "9",
    name: "Gaurav Chaudhary",
    position: "Resource Head",
    dp: "https://i.ibb.co/KWSqjQv/gaurav-chaudhary.jpg",
    insta: "https://www.instagram.com/Gauravjaat0511",
    email: "gaurav.20B0311022@abes.ac.in",
  },
  {
    id: "10",
    name: "Nilesh Agarwal",
    position: "Discipline Co-ordinator",
    dp: "https://i.ibb.co/pXBRPWK/nilesh-agarwal.jpg",
    insta: "https://www.instagram.com/NILESH_AGARWAL2303",
    email: "nilesh.20b0311197@abes.ac.in",
  },
  {
    id: "11",
    name: "Anshika Singh",
    position: "Treasurer",
    dp: "https://i.ibb.co/31zw3sr/anshika-singh.png",
    insta: "https://www.instagram.com/anshika_rajput07",
    email: "anshika.20b0311129@abes.ac.in",
  },
  {
    id: "12",
    name: "Tribhuvan Mishra",
    position: "NGO Relations",
    dp: "https://i.ibb.co/F4s91Nm/tribhuvan-mishra.jpg",
    insta: "https://www.instagram.com/tribhuvan0",
    email: "tribhuvan.20b0101033@abes.ac.in",
  },
  {
    id: "13",
    name: "Mohit Joshi",
    position: "Photography Head",
    dp: "https://i.ibb.co/ngzpG07/mohit-joshi.jpg",
    insta: "https://www.instagram.com/m.joshiii_05/",
    email: "mohit.20b0311199@abes.ac.in",
  },
  {
    id: "14",
    name: "Palak Sharma",
    position: "Web Admin",
    dp: "https://i.ibb.co/NZds1K5/palak-sharma.jpg",
    insta: "https://www.instagram.com/sharmapalak_23/",
    email: "palak.20b0101071@abes.ac.in",
  },
  {
    id: "15",
    name: "Aashutosh Mishra",
    position: "Event Head",
    dp: "https://i.ibb.co/Xj8vg2z/aashutosh-mishra.jpg",
    insta: "https://www.instagram.com/aashutosh_17.10/",
    email: "aashutosh.20b0101103@abes.ac.in ",
  },
];

export { ClubHeads, Core };
