const members = [
  {
    id: 1,
    teamName: "4th Year",
    members: [
      {
        id: 1,
        name: "Ayushi Jindal",
        position: "Member, Ex. Head IT",
        dp: "https://i.ibb.co/Csnt6jk/aayushi-jindal.jpg",
        insta: "https://www.instagram.com/_ayushi.27_",
        email: "ayushi.19b131040@abes.ac.in",
      },
      {
        id: 2,
        name: "Dipanshi Rawat",
        position: "Member",
        dp: "https://i.ibb.co/7Kn84CP/dipanshi-rawat.jpg",
        insta: "https://www.instagram.com/_dipanshiiii/",
        email: "dipanshi.19b131136@abes.ac.in",
      },
      {
        id: 3,
        name: "Lavi Badwal",
        position: "Member, Ex. General Secreatry",
        dp: "https://i.ibb.co/mJwnkGk/lavi-badwal.jpg",
        insta: "https://www.instagram.com/lavibadwal111/",
        email: "lavi.19b101163@abes.ac.in",
      },
      {
        id: 4,
        name: "Mukul Upadhyay",
        position: "Member",
        dp: "https://i.ibb.co/Yd8xz4k/mukul-upadhyay.jpg",
        insta: "https://www.instagram.com/notsomukul/",
        email: "mukul.19b131131@abes.ac.in",
      },
      {
        id: 5,
        name: "Prabhat Yadav",
        position: "Member, Ex. Head CSE",
        dp: "https://i.ibb.co/tC1bY2x/prabhat-yadav.jpg",
        insta: "https://www.instagram.com/Prabhat_._yadav",
        email: "prabhat.19b101037@abes.ac.in",
      },
      {
        id: 6,
        name: "Priyanshu Kashyap",
        position: "Member, Ex. Joint Secretary",
        dp: "https://i.ibb.co/1T5m9HY/priyanshu-kashyap.jpg",
        insta: "https://www.instagram.com/priyanshu_kinder2601/",
        email: "priyanshu.19b101050@abes.ac.in",
      },
      {
        id: 7,
        name: "Pushkar Bhatt",
        position: "Member, Ex. Head ME",
        dp: "https://i.ibb.co/QXTGJJc/pushkar-bhatt.jpg",
        insta: "",
        email: "pushkar.19b401018@abes.ac.in",
      },
      {
        id: 8,
        name: "Rohit Kumar",
        position: "Member, Ex. Digital Head",
        dp: "https://i.ibb.co/YcsgjRF/rohit-kumar.png",
        insta: "https://www.instagram.com/rohit.kumar.2906/",
        email: "rohit.19b101051@abes.ac.in",
      },
      {
        id: 9,
        name: "Tejasw Tomar",
        position: "Member, Ex. Resource Head",
        dp: "https://i.ibb.co/PYSNBCd/tejasw-tomar.png",
        insta: "https://www.instagram.com/imtejaswtomar/",
        email: "tejasw.19b401044@abes.ac.in",
      },
      {
        id: 10,
        name: "Tushar Tripathi",
        position: "Member, Ex. Promotion Head",
        dp: "https://i.ibb.co/jbDhNCz/tushar-tripathi.png",
        insta: "https://www.instagram.com/winsome_wolverine/",
        email: "tushar.19b131067@abes.ac.in",
      },
      {
        id: 11,
        name: "Vidushi Rastogi",
        position: "Member, Ex. Discipline Co-ordinator",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "https://www.instagram.com/vidushirastogiii/",
        email: "vidhushi.19b401056@abes.ac.in",
      },
    ],
  },
  {
    id: 1,
    teamName: "3rd Year",
    members: [
      {
        id: 1,
        name: "Aashutosh Mishra",
        position: "Event Head",
        dp: "https://i.ibb.co/Xj8vg2z/aashutosh-mishra.jpg",
        insta: "https://www.instagram.com/aashutosh_17.10/",
        email: "aashutosh.20b0101103@abes.ac.in",
      },
      {
        id: 2,
        name: "Akshat Saxena",
        position: "Member",
        dp: "https://i.ibb.co/yqtrZZm/akshat-saxena.jpg",
        insta: "",
        email: "akshat.20b0121164@abes.ac.in",
      },
      {
        id: 3,
        name: "Aman Kumar Sinha",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "aman.20b0401044@abes.ac.in",
      },
      {
        id: 4,
        name: "Ankit Kumar",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "ankit.20b0401014@abes.ac.in",
      },
      {
        id: 5,
        name: "Anshika Singh",
        position: "Treasurer",
        dp: "https://i.ibb.co/31zw3sr/anshika-singh.png",
        insta: "https://www.instagram.com/anshika_rajput07",
        email: "anshika.20b0311129@abes.ac.in",
      },
      {
        id: 6,
        name: "Deepansh",
        position: "Member",
        dp: "https://i.ibb.co/S3m68c2/deepansh-kumar.jpg",
        insta: "",
        email: "deepansh.20b0101070@abes.ac.in",
      },
      {
        id: 7,
        name: "Deepanshu Tripathi",
        position: "Member",
        dp: "https://i.ibb.co/ry83Y7s/divyanshu-gupta.jpg",
        insta: "",
        email: "deepanshu.20b0401045@abes.ac.in",
      },
      {
        id: 8,
        name: "Gaurav Chaudhary",
        position: "Resource Head",
        dp: "https://i.ibb.co/KWSqjQv/gaurav-chaudhary.jpg",
        insta: "https://www.instagram.com/Gauravjaat0511",
        email: "gaurav.20B0311022@abes.ac.in",
      },
      {
        id: 9,
        name: "Harsh Verma",
        position: "Member",
        dp: "https://i.ibb.co/5Y2NYbP/harsh-verma.jpg",
        insta: "",
        email: "harsh.20b0311146@abes.ac.in",
      },
      {
        id: 10,
        name: "Lakshya Sharma",
        position: "Senior Co-ordinator",
        dp: "https://i.ibb.co/CWTWVQW/lakshya-sharma.png",
        insta: "https://www.instagram.com/panditlakshya22",
        email: "lakshya.20b0101021@abes.ac.in",
      },
      {
        id: 11,
        name: "Maitri Katiyar",
        position: "Social Media Co-ordinator",
        dp: "https://i.ibb.co/JFQWyP5/maitri-katiyar.jpg",
        insta: "https://www.instagram.com/maitri__katiyar",
        email: "maitri.20b0101136@abes.ac.in",
      },
      {
        id: 12,
        name: "Mohit Joshi",
        position: "Photography Head",
        dp: "https://i.ibb.co/ngzpG07/mohit-joshi.jpg",
        insta: "https://www.instagram.com/m.joshiii_05/",
        email: "mohit.20b0311199@abes.ac.in",
      },
      {
        id: 13,
        name: "Mukul Sharma",
        position: "Joint Secretary",
        dp: "https://i.ibb.co/rdcFgSH/mukul-sharma.jpg",
        insta: "https://www.instagram.com/mukul_21947/",
        email: "mukul.20b0311058@abes.ac.in",
      },
      {
        id: 14,
        name: "Muskan Jaiswal",
        position: "Member",
        dp: "https://i.ibb.co/TT6frDp/muskan-jaiswal.jpg",
        insta: "",
        email: "muskan.20b0101165@abes.ac.in",
      },
      {
        id: 15,
        name: "Neelanjana",
        position: "Member",
        dp: "https://i.ibb.co/X5Wb2HL/neelanjana-singh.jpg",
        insta: "",
        email: "neelanjana.20b0101150@abes.ac.in",
      },
      {
        id: 16,
        name: "Nilesh Agarwal",
        position: "Discipline Co-ordinator",
        dp: "https://i.ibb.co/pXBRPWK/nilesh-agarwal.jpg",
        insta: "https://www.instagram.com/NILESH_AGARWAL2303",
        email: "nilesh.20b0311197@abes.ac.in",
      },
      {
        id: 17,
        name: "Palak Sharma",
        position: "Web Admin",
        dp: "https://i.ibb.co/NZds1K5/palak-sharma.jpg",
        insta: "https://www.instagram.com/sharmapalak_23/",
        email: "palak.20b0101071@abes.ac.in",
      },
      {
        id: 18,
        name: "Pankaj Kumar",
        position: "Digital Head",
        dp: "https://i.ibb.co/hgvZgHH/pankaj-kumar.png",
        insta: "https://www.instagram.com/pankajkr987",
        email: "pankaj.20b0101181@abes.ac.in",
      },
      {
        id: 19,
        name: "Prashant",
        position: "Social Media Co-ordinator",
        dp: "https://i.ibb.co/DW9HTzz/prashant-roy.jpg",
        insta: "https://www.instagram.com/Herobrahman",
        email: "prashant.20b0311133@abes.ac.in",
      },
      {
        id: 20,
        name: "Pratham Maurya",
        position: "Promotion Head",
        dp: "https://i.ibb.co/nsGLy8f/pratham-maurya.jpg",
        insta: "https://www.instagram.com/prat.ham3072",
        email: "pratham.20b0311181@abes.ac.in",
      },
      {
        id: 21,
        name: "Priya Verma",
        position: "Member",
        dp: "https://i.ibb.co/BrM92WQ/priya-verma.jpg",
        insta: "",
        email: "priya.20b0311038@abes.ac.in",
      },
      {
        id: 22,
        name: "Raghav Shah",
        position: "General Secretary",
        dp: "https://i.ibb.co/cbP942f/raghav-shah.jpg",
        insta: "https://www.instagram.com/_raghav._.daada/",
        email: "raghav.20b0311207@abes.ac.in",
      },
      {
        id: 23,
        name: "Riya Rathore",
        position: "Member",
        dp: "https://i.ibb.co/VB8NcW2/riya-rathore.png",
        insta: "",
        email: "riya.20b0101020@abes.ac.in",
      },
      {
        id: 24,
        name: "Sakshi Shakya",
        position: "Member",
        dp: "https://i.ibb.co/0hZD85G/sakshi-sakya.jpg",
        insta: "",
        email: "sakshi.20b1531132@abes.ac.in",
      },
      {
        id: 25,
        name: "Subbu Suman",
        position: "Design Head",
        dp: "https://i.ibb.co/Sfzz8GZ/subbu-suman.jpg",
        insta: "https://www.instagram.com/i_subbu.rajput",
        email: "subbu.20b0401048@abes.ac.in",
      },
      {
        id: 26,
        name: "Tanu Maurya",
        position: "Member",
        dp: "https://i.ibb.co/pyqsT2m/tanu-maurya.png",
        insta: "",
        email: "tanu.20b1541058@abes.ac.in",
      },
      {
        id: 27,
        name: "Tribhuvan Mishra",
        position: "NGO Relations",
        dp: "https://i.ibb.co/F4s91Nm/tribhuvan-mishra.jpg",
        insta: "https://www.instagram.com/tribhuvan0",
        email: "tribhuvan.20b0101033@abes.ac.in",
      },
      {
        id: 28,
        name: "Vaishnavi Mishra",
        position: "Member",
        dp: "https://i.ibb.co/gZSdrRN/vaishanavi-mishra.png",
        insta: "",
        email: "vaishnavi.20b0101031@abes.ac.in",
      },
      {
        id: 29,
        name: "Vraddhi Jain",
        position: "Member",
        dp: "https://i.ibb.co/R2PnPsZ/vraddhi-jain.png",
        insta: "",
        email: "vraddhi.20b1531139@abes.ac.in",
      },

      {
        id: 1,
        name: "Aakash Kumar Singh",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "aakash.21b0213006@abes.ac.in",
      },
      {
        id: 2,
        name: "Pulkit Jain",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "pulkit.20b0101179@abes.ac.in",
      },
    ],
  },
  {
    id: 1,
    teamName: "2nd Year",
    members: [
      {
        id: 1,
        name: "Abhishek Puri",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "abhishek.21b0101062@abes.ac.in",
      },
      {
        id: 2,
        name: "Abhishek Soni",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "abhishek.21b1531138@abes.ac.in",
      },
      {
        id: 3,
        name: "Aditya Garg",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "aditya.21b0131035@abes.ac.in",
      },
      {
        id: 4,
        name: "Aditya Gupta",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "aditya.21b0131009@abes.ac.in",
      },
      {
        id: 5,
        name: "Anash Malik",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "anash.21b1531091@abes.ac.in",
      },
      {
        id: 6,
        name: "Anjali Gupta",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "anjali.21b0101104@abes.ac.in",
      },
      {
        id: 7,
        name: "Anshika Chaudhary",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "anshika.21b1531093@abes.ac.in",
      },
      {
        id: 8,
        name: "Anshika Choudhary",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "anshika.21b1531093@abes.ac.in",
      },
      {
        id: 9,
        name: "Anshika Singh",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "aanshikasingh.0103@gmail.com",
      },
      {
        id: 10,
        name: "Anshika Singh",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "anshika.21b0131155@abes.ac.in",
      },
      {
        id: 11,
        name: "Astha Tripathi",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "astha.2021b0101150@abes.ac.in",
      },
      {
        id: 12,
        name: "Deepansh Bhardwaj",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "deepansh.21b0121063@abes.ac.in",
      },
      {
        id: 13,
        name: "Divyank Chauhan",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "divyank.21b0311014@abes.ac.in",
      },
      {
        id: 14,
        name: "Harshit Jaiswal",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "harshit.21b0311046@abes.ac.in",
      },
      {
        id: 15,
        name: "Jhanvi Anand",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "jhanvi.21b0311063@abes.ac.in",
      },
      {
        id: 16,
        name: "Keshav Sharma",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "keshav.21b0311113@abes.ac.in",
      },
      {
        id: 17,
        name: "Khyati Gupta",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "khyati.21b0131062@abes.ac.in",
      },
      {
        id: 18,
        name: "Km AKanksha",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "",
      },
      {
        id: 19,
        name: "Kunal Gupta",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "kunal.21b0311132@abes.ac.in",
      },
      {
        id: 20,
        name: "Manas Kandwal",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "manas.21b1541041@abes.ac.in",
      },
      {
        id: 21,
        name: "Nandini Maheshwari",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "Nandini.20B0101027@abes.ac.in",
      },
      {
        id: 22,
        name: "Nikhil Mandoli",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "nikhil.21b0311147@abes.ac.in",
      },
      {
        id: 23,
        name: "Om Gour",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "om.21b1541138@abes ac.in",
      },
      {
        id: 24,
        name: "Priyanshu Sahu",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "priyanshu.21b1531110@abes.ac.in",
      },
      {
        id: 25,
        name: "Rhythm Tyagi",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "rhythm.21b1531157@abes.ac.in",
      },
      {
        id: 26,
        name: "Suhani Garg",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "suhani.21b1531016@abes.ac.in",
      },
      {
        id: 27,
        name: "Vishal Prajapati",
        position: "Member",
        dp: "https://i.ibb.co/mSHCYWZ/sample.jpg",
        insta: "",
        email: "vishal.21b1531024@abes.ac.in",
      },
    ],
  },
];

export default members;
